# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IncendieMontreal
                                 A QGIS plugin
 Analyse du nombre d'individus, les adresses et les rues affectés par un incendie.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-16
        copyright            : (C) 2020 by David Ethier et Elizabeth Cauvier Charest
        email                : caue3201@usherbrooke.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IncendieMontreal class from file IncendieMontreal.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .IncendieMontreal import IncendieMontreal
    return IncendieMontreal(iface)
