# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IncendieMontreal
                                 A QGIS plugin
 Analyse du nombre d'individus, les adresses et les rues affectés par un incendie.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-03-16
        git sha              : $Format:%H$
        copyright            : (C) 2020 by David Ethier et Elizabeth Cauvier Charest
        email                : caue3201@usherbrooke.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .IncendieMontreal_dialog import IncendieMontrealDialog
import os.path


class IncendieMontreal:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IncendieMontreal_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&IncendieMontreal')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('IncendieMontreal', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/IncendieMontreal/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Incendie Montreal'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IncendieMontreal'),
                action)
            self.iface.removeToolBarIcon(action)


    def select_input_file(self):
        filename, _filter = QFileDialog.getOpenFileName(
            self.dlg, "Select input file ", "", '*.shp')
        # Add the selected filename to combobox
        self.dlg.comboBox_recens_spat.addItem(filename)
        # Obtain index of newly-added item
        index = self.dlg.comboBox_recens_spat.findText(filename)
        # Set the combobox to select the new item
        self.dlg.comboBox_recens_spat.setCurrentIndex(index)


    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(
            self.dlg, "Select   output file ", "", '*.txt')
        self.dlg.line_sortie.setText(filename)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = IncendieMontrealDialog()

        # On appelle la fonction select_input_file si le bouton toolButton_spat est cliqué
        self.dlg.toolButton_spat.clicked.connect(self.select_input_file)
        # On appelle la fonction select_output_file si le bouton toolButton_sortie est cliqué
        self.dlg.toolButton_sortie.clicked.connect(self.select_output_file)


        # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()
        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox_recens_spat.clear()
        # Populate the comboBox with names of all the loaded layers
        self.dlg.comboBox_recens_spat.addItems([layer.name() for layer in layers])

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:

            # 1. Faire le buffer sur la couche point
            # 2. Comptabiliser la population totale
            #   2.1 Faire une requête dans le CSV des AD avec les ID des AD à l'intérieur du buffer
            #   2.2 Extraire la population, faire le total
            # 3. Faire la liste des rues affectées
            #   3.1 Faire une requête dans la couche des rues, ceux qui sont contenues dans le buffer
            #   3.2 Ajouter les noms de rue à une liste
            # 4. Faire un dictionnaire des adresses affectées
            #   4.1 Faire une requête dans la couche des adresses, ceux qui sont contenues dans le buffer
            #   4.2 Ajouter les adresses comme key au dict.
            #   4.3 Extraire le nom de la rue et l'ajouter comme valeur au dictionnaire
            # 5. Formatage du fichier txt en sortie
            #   - on affiche la population totale affectée en haut du fichier
            #   - on affiche une rue
            #   - on affiche toutes les adresses affectées dans la rue

            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
